/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniandes.csw.neighborhood.resources;

import co.edu.uniandes.csw.neighborhood.dtos.ResidentLoginDetailDTO;
import co.edu.uniandes.csw.neighborhood.dtos.CommentDTO;
import co.edu.uniandes.csw.neighborhood.ejb.CommentLogic;
import co.edu.uniandes.csw.neighborhood.entities.CommentEntity;
import co.edu.uniandes.csw.neighborhood.exceptions.BusinessLogicException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import static javax.ws.rs.HttpMethod.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.PathParam;
import javax.ws.rs.WebApplicationException;

/**
 * Class implementing resource "comments".
 *
 * @author albayona
 * @version 1.0
 */
@Path("comments")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@RequestScoped
public class CommentResource {

    private static final Logger LOGGER = Logger.getLogger(CommentResource.class.getName());

    @Inject
    private CommentLogic commentLogic;

    /**
     * Creates a new comment with the information received in request, then 
     * an identical object is returned with an id generated by DB 
     *
     * @param comment {@link CommentDTO} - Resident to be persisted
     * @return JSON {@link CommentDTO} - Auto-generated comment to be persisted
     */
    @POST
    public CommentDTO createResident(CommentDTO comment) throws BusinessLogicException   {
        LOGGER.log(Level.INFO, "Creating comment from resource: input: {0}", comment);
        

        CommentDTO commentDTO = new CommentDTO(commentLogic.createComment(comment.toEntity()));

       
        LOGGER.log(Level.INFO, "Created comment from resource: output: {0}", commentDTO);
        return comment;
    }

    /**
     * Looks for all comments on application and returns them.
     *
     * @return JSONArray {@link CommentDTO} - All the comments on application if found. Otherwise, an empty list.
     */
    @GET
    public List<CommentDTO> getResidents() {
        LOGGER.info("Looking for all comments from resources: input: void");
        List<CommentDTO> comments = listEntity2DTO(commentLogic.getComments());
        LOGGER.log(Level.INFO, "Ended looking for all comments from resources: output: {0}", comments);
        return comments;
    }

    /**
     * Looks for the comment with id received in the URL y returns it.
     *
     * @param commentsId Id from wanted comment. Must be a sequence of digits.
     * @return JSON {@link CommentDTO} - Wanted comment DTO
     * @throws WebApplicationException {@link WebApplicationExceptionMapper} -
     * Logic error if not found
     */
    @GET
    @Path("{commentsId: \\d+}")
    public CommentDTO getResident(@PathParam("commentsId") Long commentsId) {
        LOGGER.log(Level.INFO, "Looking for  comment from resource: input: {0}", commentsId);
        CommentEntity commentEntity = commentLogic.getComment(commentsId);
        if (commentEntity == null) {
            throw new WebApplicationException("Resource /comments/" + commentsId + " does not exist.", 404);
        }
        CommentDTO detailDTO = new CommentDTO(commentEntity);
        LOGGER.log(Level.INFO, "Ended looking for comment from resource: output: {0}", detailDTO);
        return detailDTO;
    }
    
    

    /**
     * Updates comment with id from URL with the information contained in request body.
     *
     * @param commentId ID from comment to be updated. Must be a sequence of digits.
     * @param comment {@link CommentDTO} Resident to be updated.
     * @return JSON {@link CommentDTO} - Updated comment
     * @throws WebApplicationException {@link WebApplicationExceptionMapper} -
     * Logic error if not found
     */
    @PUT
    @Path("{commentsId: \\d+}")
    public CommentDTO updateAuthor(@PathParam("commentsId") Long commentsId, CommentDTO comment) throws BusinessLogicException  {
        LOGGER.log(Level.INFO, "Updating comment from resource: input: authorsId: {0} , author: {1}", new Object[]{commentsId, comment});
        comment.setId(commentsId);
        if (commentLogic.getComment(commentsId) == null) {
            throw new WebApplicationException("El recurso /authors/" + commentsId + " no existe.", 404);
        }
        CommentDTO detailDTO = new CommentDTO(commentLogic.updateComment(comment.toEntity()));
        LOGGER.log(Level.INFO, "Ended updating comment from resource: output: {0}", detailDTO);
       
        return detailDTO;
    }


    /**
     * Deletes the comment with the associated id received in URL
     *
     * @param commentsId id from comment to be deleted
     * @throws WebApplicationException {@link WebApplicationExceptionMapper}
     * Logic error if not found
     */
    @DELETE
    @Path("{commentsId: \\d+}")
    public void deleteResident(@PathParam("commentsId") Long commentsId)  {
        LOGGER.log(Level.INFO, "Deleting comment from resource: input: {0}", commentsId);
        if (commentLogic.getComment(commentsId) == null) {
            throw new WebApplicationException("Resource /comments/" + commentsId + " does not exist.", 404);
        }
        commentLogic.deleteComment(commentsId);
        LOGGER.info("Resident deleted from resource: output: void");
    }



    /**
     * Converts an entity list to a DTO list for comments.
     *
     * @param entityList Resident entity list to be converted.
     * @return Resident DTO list 
     */
    private List<CommentDTO> listEntity2DTO(List<CommentEntity> entityList) {
        List<CommentDTO> list = new ArrayList<>();
        for (CommentEntity entity : entityList) {
            list.add(new CommentDTO(entity));
        }
        return list;
    }
}