/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.uniandes.csw.neighborhood.resources;

import co.edu.uniandes.csw.neighborhood.dtos.ServiceDTO;

import co.edu.uniandes.csw.neighborhood.ejb.ServiceLogic;
import co.edu.uniandes.csw.neighborhood.entities.ServiceEntity;
import co.edu.uniandes.csw.neighborhood.exceptions.BusinessLogicException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.PathParam;
import javax.ws.rs.WebApplicationException;

/**
 * Class implementing resource "services".
 *
 * @author k.romero
 
 */
@Path("services")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@RequestScoped
public class ServiceResource {

    private static final Logger LOGGER = Logger.getLogger(ServiceResource.class.getName());

    @Inject
    private ServiceLogic serviceLogic;

    /**
     * Creates a new service with the information received in request, then an
     * identical object is returned with an id generated by DB
     *
     * @param service {@link ServiceDTO} - Resident to be persisted
     * @return JSON {@link ServiceDTO} - Auto-generated service to be persisted
     */
    @POST
    public ServiceDTO createResident(ServiceDTO service) throws BusinessLogicException {
        LOGGER.log(Level.INFO, "Creating service from resource: input: {0}", service);

        ServiceDTO serviceDTO = new ServiceDTO(serviceLogic.createService(service.toEntity()));

        LOGGER.log(Level.INFO, "Created service from resource: output: {0}", serviceDTO);
        return serviceDTO;
    }

    /**
     * Looks for all services on application and returns them.
     *
     * @return JSONArray {@link ServiceDetailDTO} - All the services on application
     * if found. Otherwise, an empty list.
     */
    @GET
    public List<ServiceDTO> getResidents() {
        LOGGER.info("Looking for all services from resources: input: void");
        List<ServiceDTO> services = listEntity2DTO(serviceLogic.getServices());
        LOGGER.log(Level.INFO, "Ended looking for all services from resources: output: {0}", services);
        return services;
    }

    /**
     * Looks for the service with id received in the URL y returns it.
     *
     * @param servicesId Id from wanted service. Must be a sequence of digits.
     * @return JSON {@link ServiceDetailDTO} - Wanted service DTO
     * @throws WebApplicationException {@link WebApplicationExceptionMapper} -
     * Logic error if not found
     */
    @GET
    @Path("{servicesId: \\d+}")
    public ServiceDTO getResident(@PathParam("servicesId") Long servicesId) {
        LOGGER.log(Level.INFO, "Looking for  service from resource: input: {0}", servicesId);
        ServiceEntity serviceEntity = serviceLogic.getService(servicesId);
        if (serviceEntity == null) {
            throw new WebApplicationException("Resource /services/" + servicesId + " does not exist.", 404);
        }
        ServiceDTO detailDTO = new ServiceDTO(serviceEntity);
        LOGGER.log(Level.INFO, "Ended looking for service from resource: output: {0}", detailDTO);
        return detailDTO;
    }

    /**
     * Updates service with id from URL with the information contained in request
     * body.
     *
     * @param serviceId ID from service to be updated. Must be a sequence of digits.
     * @param service {@link ServiceDetailDTO} Resident to be updated.
     * @return JSON {@link ServiceDetailDTO} - Updated service
     * @throws WebApplicationException {@link WebApplicationExceptionMapper} -
     * Logic error if not found
     */
    @PUT
    @Path("{servicesId: \\d+}")
    public ServiceDTO updateAuthor(@PathParam("servicesId") Long servicesId, ServiceDTO service) throws BusinessLogicException {
        LOGGER.log(Level.INFO, "Updating service from resource: input: authorsId: {0} , author: {1}", new Object[]{servicesId, service});
        service.setTitle(servicesId+"");
        if (serviceLogic.getService(servicesId) == null) {
             throw new WebApplicationException("Resource /services/" + servicesId + " does not exist.", 404);
        }
        ServiceDTO detailDTO = new ServiceDTO(serviceLogic.updateService(servicesId,service.toEntity()));
        LOGGER.log(Level.INFO, "Ended updating service from resource: output: {0}", detailDTO);

        return detailDTO;
    }

    /**
     * Deletes the service with the associated id received in URL
     *
     * @param servicesId id from service to be deleted
     * @throws WebApplicationException {@link WebApplicationExceptionMapper}
     * Logic error if not found
     */
    @DELETE
    @Path("{servicesId: \\d+}")
    public void deleteResident(@PathParam("servicesId") Long servicesId) throws BusinessLogicException {
        LOGGER.log(Level.INFO, "Deleting service from resource: input: {0}", servicesId);
        if (serviceLogic.getService(servicesId) == null) {
            throw new WebApplicationException("Resource /services/" + servicesId + " does not exist.", 404);
        }
        serviceLogic.deleteService(servicesId);
        LOGGER.info("Resident deleted from resource: output: void");
    }

    /**
     *
     * Connects /services route with /members route which are dependent of service
     * resource, by redirecting to the service managing the URL segment in
     * charge of the members
     *
     * @param serviceId id from service from which the resource is being accessed
     * @return members resource from the specified service
     */

    @Path("{servicesId: \\d+}/members")
    public Class<ServiceResource> getServiceMemberResource(@PathParam("servicesId") Long servicesId) {
        if (serviceLogic.getService(servicesId) == null) {
            throw new WebApplicationException("Resource /services/" + servicesId + " does not exist.", 404);
        }
        return ServiceResource.class;
    }

    /**
     * Converts an entity list to a DTO list for services.
     *
     * @param entityList Resident entity list to be converted.
     * @return Resident DTO list
     */
    private List<ServiceDTO> listEntity2DTO(List<ServiceEntity> entityList) {
        List<ServiceDTO> list = new ArrayList<>();
        for (ServiceEntity entity : entityList) {
            list.add(new ServiceDTO(entity));
        }
        return list;
    }
}
