
DELETE FROM BUSINESSENTITY;
DELETE FROM COMMENTENTITY;
DELETE FROM EVENTENTITY;
DELETE FROM FAVORENTITY;
DELETE FROM GROUPENTITY;
DELETE FROM LOCATIONENTITY;
DELETE FROM NEIGHBORHOODENTITY;
DELETE FROM NOTIFICATIONENTITY;
DELETE FROM POSTENTITY;
DELETE FROM RESIDENTLOGINENTITY;
DELETE FROM RESIDENTPROFILEENTITY;
DELETE FROM SERVICEENTITY;

INSERT INTO NEIGHBORHOODENTITY(LOCALITY,"NAME",NUMBEROFRESIDENTS) VALUES ('NN', 'MONJES', 0);



