DELETE FROM BUSINESSENTITY;
DELETE FROM RESIDENTLOGINENTITY;
DELETE FROM LOCATIONENTITY;
DELETE FROM COMMENTENTITY;
DELETE FROM EVENTENTITY;
DELETE FROM GROUPENTITY;
DELETE FROM NOTIFICATIONENTITY;
DELETE FROM POSTENTITY;
DELETE FROM SERVICEENTITY;
DELETE FROM RESIDENTPROFILEENTITY;
DELETE FROM NEIGHBORHOODENTITY;
DELETE FROM FAVORENTITY;
DELETE FROM RESIDENTLOGIN;




-- INSERT INTO NEIGHBORHOODENTITY(LOCALITY,"NAME",NUMBEROFRESIDENTS) VALUES ('NN', 'MONJES', 0);
-- INSERT INTO NEIGHBORHOODENTITY(LOCALITY,"NAME",NUMBEROFRESIDENTS) VALUES ('NN', 'Normandia', 0);
-- 

