
DELETE FROM BUSINESSENTITY;
DELETE FROM COMMENTENTITY;
DELETE FROM EVENTENTITY;
DELETE FROM FAVORENTITY;
DELETE FROM GROUPENTITY;
DELETE FROM LOCATIONENTITY;
DELETE FROM NEIGHBORHOODENTITY;
DELETE FROM NOTIFICATIONENTITY;
DELETE FROM POSTENTITY;
DELETE FROM RESIDENTLOGINENTITY;
DELETE FROM RESIDENTPROFILEENTITY;
DELETE FROM SERVICEENTITY;



INSERT INTO RESIDENTPROFILEENTITY(ADDRESS,EMAIL,"NAME",NICKNAME,PHONENUMBER,PREFERENCES,PROOFOFRESIDENCE) VALUES('CRA 73','AB@HOTMAIL.COM', 'Andres Bayona', 'AB', '1222131', 'NN', 'link');
INSERT INTO RESIDENTPROFILEENTITY(ADDRESS,EMAIL,"NAME",NICKNAME,PHONENUMBER,PREFERENCES,PROOFOFRESIDENCE) VALUES('CRA 74','ABc@HOTMAIL.COM', 'Andres Bayona', 'AB', '1222132', 'NN', 'link');
